{% set daily_work_dir = '%s' % (data_dir) %}
{% set dataset_path = '%s' % (baseline_dataset_dir) %}
{% set daily_work_dir_parent = "/".join(daily_work_dir.split('/')[:-1]) %}
{% set datset_dirname = daily_work_dir.split('/')[-1] %}
{% set datset_patches_dirname = datset_dirname+'_patches_int' %}
{% set caffe_python_dir = '%s' % (caffe_python_dir) %}



---
- utils.filesystem.ensure_dirs:
    desc: 'create dirs'
    input:
      dirs:
      - {{daily_work_dir}}/
      - {{daily_work_dir}}/JPEGImages
      - {{daily_work_dir}}/Annotations
      - {{caffe_python_dir}}/build_{{datset_dirname}}

- utils.shell.run_system_commands:
    desc: 'prepare baseline data'
    cwd: {{daily_work_dir}}
    input:
      cmd_lines:
        - cp -rf {{dataset_path}}/JPEGImages  {{daily_work_dir}}/
        - cp -rf {{dataset_path}}/Annotations  {{daily_work_dir}}/
        - cp /ssd/hnren/Data/dataset_pipe/dataset_lib/labelmap_voc.prototxt {{daily_work_dir}}/
        - cp /ssd/hnren/Data/dataset_pipe/process/pascal_process/create_* {{daily_work_dir}}/

# - utils.shell.run_system_commands:
#     desc: 'build caffe for creat_data.sh'
#     cwd: {{caffe_python_dir}}/build_{{datset_dirname}}
#     input:
#       cmd_lines:
#         - cmake ../
#         - make -j
#         - make pycaffe


- process.pascal_process.cls.run:
    desc: 'gen pascal ImageSet/Main'
    cwd: {{daily_work_dir}}
    input:
      src_path: {{daily_work_dir}}

- utils.shell.run_system_commands:
    desc: 'creat list and data for pascal'
    cwd: {{daily_work_dir}}
    input:
      cmd_lines:
        - chmod a+x {{daily_work_dir}}/create_list.sh
        - chmod a+x {{daily_work_dir}}/create_data.sh
        - {{daily_work_dir}}/create_list.sh {{daily_work_dir_parent}} {{datset_dirname}}
        - {{daily_work_dir}}/create_data.sh {{caffe_python_dir}} {{daily_work_dir_parent}} {{datset_dirname}} {{daily_work_dir}}/labelmap_voc.prototxt

- process.split_patches_pascal.gen_size_dataset.gen_patches_voc2voc_format:
    desc: 'gen patcehs voc format datasets'
    cwd: {{daily_work_dir_parent}}
    input:
      dataset_list: [{{datset_dirname}}]
      src_refine_rectangle_size: 0.62
      req_imgsize: 300
      img_output_size: 300
      gen_gt_rect: False

- process.split_patches_pascal.filter_subset.run:
    desc: 'filter set with ratio,randomly'
    input:
      src_origin_set_file: {{daily_work_dir_parent}}/{{datset_patches_dirname}}/

- statistic.data_distribution.statistic_bbox_distribution:
    desc: 'statistic_bbox_distribution'
    input:
      src_xml_dir:
      src_img_dir:
      src_sml_size_thresh: 10